# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qmlstyles.ui'
#
# Created: Wed Jan  7 03:32:46 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_QmlStylesForm(object):
    def setupUi(self, QmlStylesForm):
        QmlStylesForm.setObjectName("QmlStylesForm")
        QmlStylesForm.resize(896, 514)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(QmlStylesForm)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbnLoadStyle = QtGui.QPushButton(QmlStylesForm)
        self.pbnLoadStyle.setObjectName("pbnLoadStyle")
        self.verticalLayout.addWidget(self.pbnLoadStyle)
        self.pbnDefaultStyle = QtGui.QPushButton(QmlStylesForm)
        self.pbnDefaultStyle.setObjectName("pbnDefaultStyle")
        self.verticalLayout.addWidget(self.pbnDefaultStyle)
        self.pbnLoadColormapFromBand = QtGui.QPushButton(QmlStylesForm)
        self.pbnLoadColormapFromBand.setObjectName("pbnLoadColormapFromBand")
        self.verticalLayout.addWidget(self.pbnLoadColormapFromBand)
        self.pbnClose = QtGui.QPushButton(QmlStylesForm)
        self.pbnClose.setObjectName("pbnClose")
        self.verticalLayout.addWidget(self.pbnClose)
        self.label = QtGui.QLabel(QmlStylesForm)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chbxSelectAllLayers = QtGui.QCheckBox(QmlStylesForm)
        self.chbxSelectAllLayers.setChecked(True)
        self.chbxSelectAllLayers.setObjectName("chbxSelectAllLayers")
        self.horizontalLayout.addWidget(self.chbxSelectAllLayers)
        self.chbxViewLayers = QtGui.QCheckBox(QmlStylesForm)
        self.chbxViewLayers.setObjectName("chbxViewLayers")
        self.horizontalLayout.addWidget(self.chbxViewLayers)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lvRasterLayers = QtGui.QListView(QmlStylesForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvRasterLayers.sizePolicy().hasHeightForWidth())
        self.lvRasterLayers.setSizePolicy(sizePolicy)
        self.lvRasterLayers.setMaximumSize(QtCore.QSize(180, 16777215))
        self.lvRasterLayers.setObjectName("lvRasterLayers")
        self.verticalLayout.addWidget(self.lvRasterLayers)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chbxTransparentLayer = QtGui.QCheckBox(QmlStylesForm)
        self.chbxTransparentLayer.setObjectName("chbxTransparentLayer")
        self.verticalLayout_2.addWidget(self.chbxTransparentLayer)
        self.label_2 = QtGui.QLabel(QmlStylesForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lvTransparency = QtGui.QListView(QmlStylesForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lvTransparency.sizePolicy().hasHeightForWidth())
        self.lvTransparency.setSizePolicy(sizePolicy)
        self.lvTransparency.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lvTransparency.setObjectName("lvTransparency")
        self.verticalLayout_2.addWidget(self.lvTransparency)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setHorizontalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.vslValueTransparency = QtGui.QSlider(QmlStylesForm)
        self.vslValueTransparency.setMinimum(0)
        self.vslValueTransparency.setMaximum(255)
        self.vslValueTransparency.setProperty("value", QtCore.QVariant(255))
        self.vslValueTransparency.setOrientation(QtCore.Qt.Vertical)
        self.vslValueTransparency.setInvertedAppearance(False)
        self.vslValueTransparency.setInvertedControls(False)
        self.vslValueTransparency.setTickPosition(QtGui.QSlider.TicksBelow)
        self.vslValueTransparency.setTickInterval(5)
        self.vslValueTransparency.setObjectName("vslValueTransparency")
        self.gridLayout.addWidget(self.vslValueTransparency, 1, 0, 5, 1)
        self.label_5 = QtGui.QLabel(QmlStylesForm)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(30, 205, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.lbTransparencyValuePercant = QtGui.QLabel(QmlStylesForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbTransparencyValuePercant.sizePolicy().hasHeightForWidth())
        self.lbTransparencyValuePercant.setSizePolicy(sizePolicy)
        self.lbTransparencyValuePercant.setMinimumSize(QtCore.QSize(37, 0))
        self.lbTransparencyValuePercant.setMaximumSize(QtCore.QSize(37, 16777215))
        self.lbTransparencyValuePercant.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbTransparencyValuePercant.setObjectName("lbTransparencyValuePercant")
        self.gridLayout.addWidget(self.lbTransparencyValuePercant, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(30, 205, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        self.label_3 = QtGui.QLabel(QmlStylesForm)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 1, 1, 1)
        self.sbxValueTransparency = QtGui.QSpinBox(QmlStylesForm)
        self.sbxValueTransparency.setMaximum(255)
        self.sbxValueTransparency.setProperty("value", QtCore.QVariant(255))
        self.sbxValueTransparency.setObjectName("sbxValueTransparency")
        self.gridLayout.addWidget(self.sbxValueTransparency, 0, 0, 1, 2)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.canvasFrame = QtGui.QFrame(QmlStylesForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvasFrame.sizePolicy().hasHeightForWidth())
        self.canvasFrame.setSizePolicy(sizePolicy)
        self.canvasFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.canvasFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.canvasFrame.setObjectName("canvasFrame")
        self.horizontalLayout_2.addWidget(self.canvasFrame)
        self.label.setBuddy(self.lvRasterLayers)
        self.label_2.setBuddy(self.lvTransparency)
        self.label_5.setBuddy(self.vslValueTransparency)
        self.lbTransparencyValuePercant.setBuddy(self.vslValueTransparency)
        self.label_3.setBuddy(self.vslValueTransparency)

        self.retranslateUi(QmlStylesForm)
        QtCore.QObject.connect(self.vslValueTransparency, QtCore.SIGNAL("valueChanged(int)"), self.sbxValueTransparency.setValue)
        QtCore.QObject.connect(self.sbxValueTransparency, QtCore.SIGNAL("valueChanged(int)"), self.vslValueTransparency.setValue)
        QtCore.QMetaObject.connectSlotsByName(QmlStylesForm)
        QmlStylesForm.setTabOrder(self.pbnLoadStyle, self.lvRasterLayers)
        QmlStylesForm.setTabOrder(self.lvRasterLayers, self.pbnDefaultStyle)
        QmlStylesForm.setTabOrder(self.pbnDefaultStyle, self.pbnLoadColormapFromBand)
        QmlStylesForm.setTabOrder(self.pbnLoadColormapFromBand, self.pbnClose)
        QmlStylesForm.setTabOrder(self.pbnClose, self.lvTransparency)
        QmlStylesForm.setTabOrder(self.lvTransparency, self.vslValueTransparency)

    def retranslateUi(self, QmlStylesForm):
        QmlStylesForm.setWindowTitle(QtGui.QApplication.translate("QmlStylesForm", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnLoadStyle.setText(QtGui.QApplication.translate("QmlStylesForm", "Load Style ...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnDefaultStyle.setText(QtGui.QApplication.translate("QmlStylesForm", "Restory Default Style", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnLoadColormapFromBand.setText(QtGui.QApplication.translate("QmlStylesForm", "Load Colormap From Band", None, QtGui.QApplication.UnicodeUTF8))
        self.pbnClose.setText(QtGui.QApplication.translate("QmlStylesForm", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("QmlStylesForm", "Raster Layers:", None, QtGui.QApplication.UnicodeUTF8))
        self.chbxSelectAllLayers.setText(QtGui.QApplication.translate("QmlStylesForm", "Select all", None, QtGui.QApplication.UnicodeUTF8))
        self.chbxViewLayers.setText(QtGui.QApplication.translate("QmlStylesForm", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.chbxTransparentLayer.setText(QtGui.QApplication.translate("QmlStylesForm", "Transnparent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("QmlStylesForm", "Transparent\n"
"pixels:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("QmlStylesForm", "Full", None, QtGui.QApplication.UnicodeUTF8))
        self.lbTransparencyValuePercant.setText(QtGui.QApplication.translate("QmlStylesForm", "100%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("QmlStylesForm", "None", None, QtGui.QApplication.UnicodeUTF8))

